# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle 	  	    Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
# Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
# Hexagonal 	  	Hn=n(2n−1) 	  	    1, 6, 15, 28, 45, ...
#
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.


def is_triangle(Tn):
    d = (8 * Tn + 1)**0.5

    if d % 1 != 0:
        return False
    else:
        n = (-1 + d) / 2
        if n % 1 == 0:
            return True
        else:
            return False

print(is_triangle(5))

def is_pentagonal(Pn):
    d = (24 * Pn + 1)

    n = (1 + d ** 0.5) / 6
    if n % 1 == 0:
        # print(f"Pn({Pn}) = {n}")
        return True
    else:
        return False


def is_hexagonal(Hn):
    d = (8 * Hn + 1)
    n = (1 + d**0.5)/4
    if n % 1 == 0:
        # print(f"Hn({Hn}) = {n}")
        return True
    else:
        return False


def find_answer(rangex):
    for a in range(rangex):
        if is_triangle(a):
            if is_pentagonal(a):
                if is_hexagonal(a):
                    print(a, "is a triangle number that is also pentagonal and hexagonal")

find_answer(5000000000)